# frozen_string_literal: true

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
end

Rake::TestTask.new(:benchmark) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_benchmark.rb']
end

desc 'Run RuboCop'
task :rubocop do
  sh 'bundle exec rubocop'
end

desc 'Auto-correct RuboCop offenses'
task :format do
  sh 'bundle exec rubocop --auto-correct'
end

desc 'Start Guard'
task :guard do
  sh 'bundle exec guard'
end

desc 'Run all quality checks (rubocop + test)'
task check: %i[rubocop test]

task default: :check
