[tox]
envlist = test,lint,type,format
skipsdist = true

[testenv]
allowlist_externals = pytest
commands = pytest

[testenv:test]
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=lib --cov-report=term-missing --verbose

[testenv:lint]
deps = ruff
commands =
    ruff check .
    ruff format --check .

[testenv:format]
deps = ruff
commands =
    ruff format .

[testenv:type]
deps =
    mypy
    pytest
commands =
    mypy lib test
